version: '3.8'

services:
  discordbot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URI=sqlite:////app/data/bot.sqlite
      - FILE_DIR=/app/data/attachments
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - proxy
    environment:
      ADMINER_DESIGN: dracula
    volumes:
      - "./login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php"
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backlink-rtr.tls=true"
      - "traefik.http.routers.backlink-rtr.entrypoints=https"
      - "traefik.http.routers.backlink-rtr.rule=Host(`spineydb.hope.fishcracker.net`) || Host(`spineydb.gamemusic.fishcracker.net`)"
      - "traefik.http.routers.backlink-rtr.service=backlink-svc"
      - "traefik.http.services.backlink-svc.loadbalancer.server.port=8080"

  attachments:
    restart: unless-stopped
    build:
      context: ./frontend_attachments
      dockerfile: Dockerfile
    # ports:
    #   - 3006:80
    networks:
      - proxy
    volumes:
      - ./frontend_attachments:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URI=sqlite:////app/data/bot.sqlite
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gmattach-nginx-rtr.tls=true"
      - "traefik.http.routers.gmattach-nginx-rtr.entrypoints=https"
      - "traefik.http.routers.gmattach-nginx-rtr.rule=Host(`gm-art.hope.fishcracker.net`) || Host(`art.gamemusic.fishcracker.net`)"
      - "traefik.http.routers.gmattach-nginx-rtr.service=gmattach-nginx-svc"
      - "traefik.http.services.gmattach-nginx-svc.loadbalancer.server.port=80"

networks:
  proxy:
    name: proxy
    external: true
