version: '3.8'

services:
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URI=sqlite:////app/data/bot.sqlite
    env_file:
      - .env
    volumes:
      - ./data:/app/data
