from datetime import datetime

# "Complete" Response from the Open Weather Map API.
# See https://openweathermap.org/current for more.
owm_json_data_complete = {
    "coord": {"lon": -122.0842, "lat": 37.4224},
    "weather": [
        {"id": 502, "main": "Rain", "description": "heavy intensity rain", "icon": "10n"},
        {"id": 701, "main": "Mist", "description": "mist", "icon": "50n"},
    ],
    "base": "stations",
    "main": {
        "temp": 13.1,
        "feels_like": 12.87,
        "temp_min": 11.77,
        "temp_max": 14.18,
        "pressure": 1014,
        "humidity": 92,
    },
    "visibility": 4828,
    "wind": {"speed": 3.6, "deg": 110, "gust": 5.6},
    "rain": {"1h": 5.31},
    "snow": {"1h": 1.2},
    "clouds": {"all": 100},
    "dt": 1703982775,
    "sys": {"type": 2, "id": 2010364, "country": "US", "sunrise": 1703949739, "sunset": 1703984341},
    "timezone": -28800,
    "id": 5375480,
    "name": "Mountain View",
    "cod": 200,
}

# A timezone offset of 0 caused a bug because `some_truthy_time and 0` is False.
owm_json_utc_location = {
    "coord": {"lon": -1.8287, "lat": 51.1788},
    "weather": [{"id": 801, "main": "Clouds", "description": "few clouds", "icon": "02n"}],
    "base": "stations",
    "main": {"temp": 5.13, "feels_like": -1.43, "temp_min": -4.56, "temp_max": 6.04, "pressure": 985, "humidity": 91},
    "visibility": 10000,
    "wind": {"speed": 5.14, "deg": 220},
    "clouds": {"all": 20},
    "dt": 1704001975,
    "sys": {"type": 2, "id": 2003051, "country": "GB", "sunrise": 1704010285, "sunset": 1704038910},
    "timezone": 0,
    "id": 2657355,
    "name": "Amesbury",
    "cod": 200,
}

currentweather_expected_utc_location = {
    "last_updated": datetime(2023, 12, 30, 21, 52, 55),
    "conditions": "few clouds",
    "icon": "02n",
    "temperature": 5.13,
    "feels_like": -1.43,
    "humidity": 91,
    "pressure": 985,
    "visibility": 10000,
    "wind_speed": 5.14,
    "wind_direction": "SW",
    "clouds": 20,
    "sunrise": datetime(2023, 12, 31, 0, 11, 25),
    "sunset": datetime(2023, 12, 31, 8, 8, 30),
    "name": "Amesbury",
    "country": "GB",
}


# The minimum accepted fields for a `CurrentWeather` object.
owm_json_data_minimal = {
    "main": {
        "temp": 15.8,
    },
    "dt": 1703918849,
    "timezone": -28800,
    "name": "Mountain View",
    "cod": 200,
}


# A dictionary used to check the values for each attribute of the above
# OWM API response, once it's processed by `CurrentWeather`.
currentweather_expected_complete = {
    "last_updated": datetime(2023, 12, 30, 8, 32, 55),
    "conditions": "heavy intensity rain",
    "icon": "10n",
    "temperature": 13.1,
    "feels_like": 12.87,
    "humidity": 92,
    "pressure": 1014,
    "visibility": 4828,
    "wind_speed": 3.6,
    "wind_gust": 5.6,
    "wind_direction": "ESE",
    "clouds": 100,
    "rain_last_hour": 5.31,
    "snow_last_hour": 1.2,
    "sunrise": datetime(2023, 12, 29, 23, 22, 19),
    "sunset": datetime(2023, 12, 30, 8, 59, 1),
    "name": "Mountain View",
    "country": "US",
}


# A dictionary for checking values of the minimum attributes needed to
# instantiate a `CurrentWeather` object.
currentweather_expected_minimal = {
    "name": "Mountain View",
    "temperature": 15.8,
    "last_updated": datetime(2023, 12, 29, 14, 47, 29),
}

# A grid response from https://api.weather.gov/points/39.7456,-97.0892
forecast_weather_grid_response = {'@context': ['https://geojson.org/geojson-ld/geojson-context.jsonld',
  {'@version': '1.1',
   'wx': 'https://api.weather.gov/ontology#',
   's': 'https://schema.org/',
   'geo': 'http://www.opengis.net/ont/geosparql#',
   'unit': 'http://codes.wmo.int/common/unit/',
   '@vocab': 'https://api.weather.gov/ontology#',
   'geometry': {'@id': 's:GeoCoordinates', '@type': 'geo:wktLiteral'},
   'city': 's:addressLocality',
   'state': 's:addressRegion',
   'distance': {'@id': 's:Distance', '@type': 's:QuantitativeValue'},
   'bearing': {'@type': 's:QuantitativeValue'},
   'value': {'@id': 's:value'},
   'unitCode': {'@id': 's:unitCode', '@type': '@id'},
   'forecastOffice': {'@type': '@id'},
   'forecastGridData': {'@type': '@id'},
   'publicZone': {'@type': '@id'},
   'county': {'@type': '@id'}}],
 'id': 'https://api.weather.gov/points/39.7456,-97.0892',
 'type': 'Feature',
 'geometry': {'type': 'Point', 'coordinates': [-97.0892, 39.7456]},
 'properties': {'@id': 'https://api.weather.gov/points/39.7456,-97.0892',
  '@type': 'wx:Point',
  'cwa': 'TOP',
  'forecastOffice': 'https://api.weather.gov/offices/TOP',
  'gridId': 'TOP',
  'gridX': 32,
  'gridY': 81,
  'forecast': 'https://api.weather.gov/gridpoints/TOP/32,81/forecast',
  'forecastHourly': 'https://api.weather.gov/gridpoints/TOP/32,81/forecast/hourly',
  'forecastGridData': 'https://api.weather.gov/gridpoints/TOP/32,81',
  'observationStations': 'https://api.weather.gov/gridpoints/TOP/32,81/stations',
  'relativeLocation': {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [-97.086661, 39.679376]},
   'properties': {'city': 'Linn',
    'state': 'KS',
    'distance': {'unitCode': 'wmoUnit:m', 'value': 7366.9851976444},
    'bearing': {'unitCode': 'wmoUnit:degree_(angle)', 'value': 358}}},
  'forecastZone': 'https://api.weather.gov/zones/forecast/KSZ009',
  'county': 'https://api.weather.gov/zones/county/KSC201',
  'fireWeatherZone': 'https://api.weather.gov/zones/fire/KSZ009',
  'timeZone': 'America/Chicago',
  'radarStation': 'KTWX'}}

# A grid forecast from https://api.weather.gov/gridpoints/TOP/32,81/forecast
forecast_weather_grid_seven_day = {'@context': ['https://geojson.org/geojson-ld/geojson-context.jsonld',
  {'@version': '1.1',
   'wx': 'https://api.weather.gov/ontology#',
   'geo': 'http://www.opengis.net/ont/geosparql#',
   'unit': 'http://codes.wmo.int/common/unit/',
   '@vocab': 'https://api.weather.gov/ontology#'}],
 'type': 'Feature',
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-97.1089731, 39.7668263],
    [-97.1085269, 39.7447788],
    [-97.0798467, 39.7451195],
    [-97.08028680000001, 39.767167],
    [-97.1089731, 39.7668263]]]},
 'properties': {'updated': '2024-01-15T23:27:23+00:00',
  'units': 'us',
  'forecastGenerator': 'BaselineForecastGenerator',
  'generatedAt': '2024-01-16T03:21:27+00:00',
  'updateTime': '2024-01-15T23:27:23+00:00',
  'validTimes': '2024-01-15T17:00:00+00:00/P7DT11H',
  'elevation': {'unitCode': 'wmoUnit:m', 'value': 441.96},
  'periods': [{'number': 1,
    'name': 'Tonight',
    'startTime': '2024-01-15T21:00:00-06:00',
    'endTime': '2024-01-16T06:00:00-06:00',
    'isDaytime': False,
    'temperature': -12,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -23.333333333333332},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 82},
    'windSpeed': '10 mph',
    'windDirection': 'W',
    'icon': 'https://api.weather.gov/icons/land/night/cold?size=medium',
    'shortForecast': 'Clear',
    'detailedForecast': 'Clear, with a low around -12. Wind chill values as low as -29. West wind around 10 mph, with gusts as high as 20 mph.'},
   {'number': 2,
    'name': 'Tuesday',
    'startTime': '2024-01-16T06:00:00-06:00',
    'endTime': '2024-01-16T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 12,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -15.555555555555555},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 88},
    'windSpeed': '10 to 15 mph',
    'windDirection': 'W',
    'icon': 'https://api.weather.gov/icons/land/day/skc?size=medium',
    'shortForecast': 'Sunny',
    'detailedForecast': 'Sunny, with a high near 12. Wind chill values as low as -31. West wind 10 to 15 mph, with gusts as high as 20 mph.'},
   {'number': 3,
    'name': 'Tuesday Night',
    'startTime': '2024-01-16T18:00:00-06:00',
    'endTime': '2024-01-17T06:00:00-06:00',
    'isDaytime': False,
    'temperature': 3,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -13.88888888888889},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 90},
    'windSpeed': '10 to 15 mph',
    'windDirection': 'SW',
    'icon': 'https://api.weather.gov/icons/land/night/cold?size=medium',
    'shortForecast': 'Mostly Clear',
    'detailedForecast': 'Mostly clear, with a low around 3. Wind chill values as low as -11. Southwest wind 10 to 15 mph, with gusts as high as 20 mph.'},
   {'number': 4,
    'name': 'Wednesday',
    'startTime': '2024-01-17T06:00:00-06:00',
    'endTime': '2024-01-17T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 26,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -6.666666666666667},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 96},
    'windSpeed': '5 to 10 mph',
    'windDirection': 'S',
    'icon': 'https://api.weather.gov/icons/land/day/sct?size=medium',
    'shortForecast': 'Mostly Sunny',
    'detailedForecast': 'Mostly sunny, with a high near 26. Wind chill values as low as -3. South wind 5 to 10 mph.'},
   {'number': 5,
    'name': 'Wednesday Night',
    'startTime': '2024-01-17T18:00:00-06:00',
    'endTime': '2024-01-18T06:00:00-06:00',
    'isDaytime': False,
    'temperature': 9,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -8.333333333333334},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 100},
    'windSpeed': '5 to 10 mph',
    'windDirection': 'NE',
    'icon': 'https://api.weather.gov/icons/land/night/cold?size=medium',
    'shortForecast': 'Mostly Cloudy',
    'detailedForecast': 'Mostly cloudy, with a low around 9. Northeast wind 5 to 10 mph.'},
   {'number': 6,
    'name': 'Thursday',
    'startTime': '2024-01-18T06:00:00-06:00',
    'endTime': '2024-01-18T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 17,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent', 'value': 20},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -9.444444444444445},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 100},
    'windSpeed': '10 mph',
    'windDirection': 'N',
    'icon': 'https://api.weather.gov/icons/land/day/bkn/snow,20?size=medium',
    'shortForecast': 'Partly Sunny then Slight Chance Light Snow',
    'detailedForecast': 'A slight chance of snow after noon. Partly sunny, with a high near 17. North wind around 10 mph. Chance of precipitation is 20%. Little or no snow accumulation expected.'},
   {'number': 7,
    'name': 'Thursday Night',
    'startTime': '2024-01-18T18:00:00-06:00',
    'endTime': '2024-01-19T06:00:00-06:00',
    'isDaytime': False,
    'temperature': -4,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent', 'value': 20},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -11.11111111111111},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 94},
    'windSpeed': '15 mph',
    'windDirection': 'N',
    'icon': 'https://api.weather.gov/icons/land/night/snow,20/cold?size=medium',
    'shortForecast': 'Slight Chance Light Snow then Partly Cloudy',
    'detailedForecast': 'A slight chance of snow before midnight. Partly cloudy, with a low around -4. North wind around 15 mph, with gusts as high as 25 mph. Chance of precipitation is 20%.'},
   {'number': 8,
    'name': 'Friday',
    'startTime': '2024-01-19T06:00:00-06:00',
    'endTime': '2024-01-19T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 8,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -16.666666666666668},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 96},
    'windSpeed': '10 to 15 mph',
    'windDirection': 'NW',
    'icon': 'https://api.weather.gov/icons/land/day/cold?size=medium',
    'shortForecast': 'Sunny',
    'detailedForecast': 'Sunny, with a high near 8. Northwest wind 10 to 15 mph, with gusts as high as 25 mph.'},
   {'number': 9,
    'name': 'Friday Night',
    'startTime': '2024-01-19T18:00:00-06:00',
    'endTime': '2024-01-20T06:00:00-06:00',
    'isDaytime': False,
    'temperature': -12,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -18.88888888888889},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 100},
    'windSpeed': '5 to 10 mph',
    'windDirection': 'N',
    'icon': 'https://api.weather.gov/icons/land/night/cold?size=medium',
    'shortForecast': 'Partly Cloudy',
    'detailedForecast': 'Partly cloudy, with a low around -12. North wind 5 to 10 mph.'},
   {'number': 10,
    'name': 'Saturday',
    'startTime': '2024-01-20T06:00:00-06:00',
    'endTime': '2024-01-20T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 12,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -14.444444444444445},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 100},
    'windSpeed': '5 to 10 mph',
    'windDirection': 'SE',
    'icon': 'https://api.weather.gov/icons/land/day/sct?size=medium',
    'shortForecast': 'Mostly Sunny',
    'detailedForecast': 'Mostly sunny, with a high near 12.'},
   {'number': 11,
    'name': 'Saturday Night',
    'startTime': '2024-01-20T18:00:00-06:00',
    'endTime': '2024-01-21T06:00:00-06:00',
    'isDaytime': False,
    'temperature': 5,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -13.333333333333334},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 88},
    'windSpeed': '15 mph',
    'windDirection': 'SE',
    'icon': 'https://api.weather.gov/icons/land/night/cold?size=medium',
    'shortForecast': 'Mostly Cloudy',
    'detailedForecast': 'Mostly cloudy, with a low around 5.'},
   {'number': 12,
    'name': 'Sunday',
    'startTime': '2024-01-21T06:00:00-06:00',
    'endTime': '2024-01-21T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 29,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -4.444444444444445},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 97},
    'windSpeed': '15 mph',
    'windDirection': 'S',
    'icon': 'https://api.weather.gov/icons/land/day/bkn?size=medium',
    'shortForecast': 'Partly Sunny',
    'detailedForecast': 'Partly sunny, with a high near 29.'},
   {'number': 13,
    'name': 'Sunday Night',
    'startTime': '2024-01-21T18:00:00-06:00',
    'endTime': '2024-01-22T06:00:00-06:00',
    'isDaytime': False,
    'temperature': 24,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': -3.3333333333333335},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 98},
    'windSpeed': '15 to 20 mph',
    'windDirection': 'S',
    'icon': 'https://api.weather.gov/icons/land/night/bkn?size=medium',
    'shortForecast': 'Mostly Cloudy',
    'detailedForecast': 'Mostly cloudy, with a low around 24.'},
   {'number': 14,
    'name': 'Monday',
    'startTime': '2024-01-22T06:00:00-06:00',
    'endTime': '2024-01-22T18:00:00-06:00',
    'isDaytime': True,
    'temperature': 36,
    'temperatureUnit': 'F',
    'temperatureTrend': None,
    'probabilityOfPrecipitation': {'unitCode': 'wmoUnit:percent',
     'value': None},
    'dewpoint': {'unitCode': 'wmoUnit:degC', 'value': 1.1111111111111112},
    'relativeHumidity': {'unitCode': 'wmoUnit:percent', 'value': 100},
    'windSpeed': '15 mph',
    'windDirection': 'S',
    'icon': 'https://api.weather.gov/icons/land/day/bkn?size=medium',
    'shortForecast': 'Mostly Cloudy',
    'detailedForecast': 'Mostly cloudy, with a high near 36.'}]}}
