"""Added last seen attributes to the User model

Revision ID: 804f54dc94cd
Revises: 6dd9b23bfed0
Create Date: 2025-03-22 22:44:22.603496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804f54dc94cd'
down_revision: Union[str, None] = '6dd9b23bfed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_line', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_line')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
